[Variables]


;==========[Day]====================
Day_Language=Arabic
Day_Scale=1.5
Day_TextSize=100
Day_Font=DecoType Thuluth II
Day_Color=52,142,194,255

;==========[Date (Gregorian)]====================
DateG_Language=English
DateG_Scale=0.8
DateG_TextSize=25
DateG_Font=Arial Rounded MT
DateG_Color=36,36,36,255

;==========[Date (Hijri)]====================
DateH_Language=English
DateH_Scale=0.8
DateH_TextSize=25
DateH_Font=Arial Rounded MT
DateH_Color=36,36,36,255

;==========[Clock]====================
Clock_Language=English
Clock_Scale=0.8
Clock_TextSize=25
Clock_Font=Arial Rounded MT
Clock_Color=36,36,36,255

==============================
; No manual adjustment needed for colors. Double-click the overlay to open the color-picker.
; Do not forget to right-click > Refresh skin to see changes.
